### ISSUE TITLE
Very useful script

### ISSUE THREAD

**Issue by vinesmsuic** [PolyU-Robocon/ROS-Auto-Setup-Script#1]
very useful, cant even install ROS without this useful script
how about writing another one for ROS melodic?

**Comment by supercrazysam** [comment]
Max so noob, cannot even install ros without asking for a script.

Come on... copy the commands from ros installation guide and automate it yourself.

**Comment by vinesmsuic** [comment]
> Max so noob, cannot even install ros without asking for a script.
> 
> Come on... copy the commands from ros installation guide and automate it yourself.

bruh, can you even identify irony?

**Comment by supercrazysam** [comment]
@vinesmsuic I diagnose you with gay
